### ISSUE TITLE
Database integration

### ISSUE THREAD

**Issue by juliaofferman** [hannaco/SpotiFry#16]
## Epic
Integrate usage of MongoDB into react code.
## User Stories

- [x] As a user, I should be registered in the SpotiFry database when I login for the first time.
- [x] As a user, each of my newly created playlists should be stored by Spotifry.
- [x] As a user, I should be able to view my past custom playlists through SpotiFry.

**Comment by bulaienTang** [comment]
All generated playlists are stored in the data base
Last five playlists now can be viewed at homepage
