### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by hannaco** [hannaco/SpotiFry#3]
## Epic
Setup MongoDB database and schema in order to store user ID and previously generated playlists

## Tasks
- [x] Plan schema/how to store playlists
- [x] Create database
- [x] Write functions to add new users/playlists

**Comment by juliaofferman** [comment]
Schema: https://drive.google.com/file/d/1PrOkMwD379cN_uoYJlAaxa58q-FM4LH8/view?usp=share_link
Database located in Mongo
database directory holds functions for adding, deleting entries
